### ISSUE TITLE
With Scala 2.11 and sbt

### ISSUE THREAD

**Issue by nlhkh** [FaKod/neo4j-scala#35]
It seems that I cannot make this work with SBT. I added the line

     "eu.fakod" % "neo4j-scala_2.10" % "0.3.0"

to my build.sbt file, and it seems to want some other library.

Also, it says neo4j-scala_2.10, so does this work with Scala 2.11?

Thanks

**Comment by FaKod** [comment]
There is no direct support for Scala 2.11.
But feel free to compile neo4j-scala for 2.11 yourself?
