### ISSUE TITLE
Traversing results

### ISSUE THREAD

**Issue by michaelmcv** [FaKod/neo4j-scala#37]
I was having a play around with this library, and I am attempting to retrieve a node related to my reference node via a relationship

<pre>
val rivals = rootUserNode.doTraverse[User](follow(BREADTH_FIRST) -<- "RIVAL", 100, ReturnAllButStartNode)
rivals.toList
</pre>
rivals is being returned as an empty list, I debugged this through to the actual underlying rest response from the neo4j server, and I can see the node I am interested in within the json response from neo4j.

Digging into the scala code a bit further, it looks like a specific property key
<pre> "__CLASS__" </pre>
is used during serialisation / de-serlisation between Node and case classes. My data is loaded via a separate process, not through this library. Am I understanding the scala code correctly, in that I will not be able to return a node through the type traverser if it has not been created via this specific library?

Thanks!

**Comment by FaKod** [comment]
yes, you are right. Neo4j-scala uses this information for case class deserialization.
But it should work if you create a __CLASS__ property in your own code.

**Comment by michaelmcv** [comment]
Cheers for getting back to me - I will leave it at the moment as I don't want to create a hard link (name of the class) between the two separate processs I have. 
Next time I am using scala and neo4j I try using your library while I am creating the data as well. Thanks!
